// <auto-generated />
namespace Issue_Register.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changePost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changePost));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041812081_changePost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
